#!/bin/zsh

HISTFILE=~/.cache/.histfile
HISTSIZE=1000
SAVEHIST=1000
#Enable colors
autoload -Uz colors && colors
#use vi mode
bindkey -v
#256 color mode
TERM=xterm-256color
setopt NO_BEEP
# Share history between all shells
setopt sharehistory
