#!/bin/zsh
if which nvim>/dev/null 2>&1; then
  alias vi=nvim
elif which vim>/dev/null 2>&1; then
  alias vi=vim
fi
# Color aliases
if command -V dircolors >/dev/null 2>&1; then
	eval "$(dircolors -b)"
	# Only alias ls colors if dircolors is installed
	alias ls="ls -F --color=auto"
	alias dir="dir --color=auto"
	alias vdir="vdir --color=auto"
fi
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
# make less accept color codes and re-output them
alias less="less -R"

alias l="ls -CF"
alias ll="ls -lh"
alias la="ls -A"
alias sl="ls"
alias sudo="sudo "
alias dh="dirs -v"
